apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}