{{- if .Values.persistence.wordpress.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.wordpress.accessMode }}
  storageClassName: {{ .Values.persistence.wordpress.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.wordpress.size }}
{{- end }}